version: '3.8'

services:
  # ddcmodel:
  #   image: cmodeldocker:latest
  #   ports:
  #     - "8887:8888"
  #   volumes:
  #     - ../script:/script
  #     - ../initial:/initial
  #     - ../data:/data

  #   networks:
  #     - web  
  #   depends_on:
  #     mongo:
  #       condition: service_started
  #       restart: true




  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: tyjWbtU4DRnuXqdhK
    networks:
      - web
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db:rw

      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: tyjWbtU4DRnuXqdhK
      ME_CONFIG_MONGODB_URL: mongodb://root:tyjWbtU4DRnuXqdhK@mongo:27017/
      ME_CONFIG_BASICAUTH: false

    networks:
      - web


networks:
  web:
    name: cmodel_net